name: Generate Pacman

on:
  workflow_dispatch:

permissions:
  contents: write   # 🔥 هذا هو الحل المهم

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman
        run: |
          mkdir -p dist
          curl -o dist/pacman.svg https://raw.githubusercontent.com/abozanona/pacman-contribution-graph/main/pacman.svg
          curl -o dist/pacman-dark.svg https://raw.githubusercontent.com/abozanona/pacman-contribution-graph/main/pacman-dark.svg

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
